spring:
  application:
    name: dropbox
    security:
      jwt:
        secret-key: 931f9ef08d0750791fdf4048d04adb53198e90edcbee08bfc5ad752323fee103
        expiration: 8640000
  datasource:
    url: jdbc:postgresql://ep-bitter-heart-a8r92nax-pooler.eastus2.azure.neon.tech/dropbox
    username: neondb_owner
    password: npg_LKfT5O3HamiG
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
server:
  servlet:
    context-path: /api/v1